name:                hspec-webdriver-toolkit
version:             0.1.0.0
github:              "githubuser/hspec-webdriver-toolkit"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2019 Tom McLaughlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Batteries-including toolkit for running Selenium WebDriver tests
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hspec-webdriver-simple#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- convertible
- data-default
- directory
- exceptions
- filepath
- hspec
- hspec-core
- http-client
- http-conduit
- interpolate
- lens-aeson
- lens
- lifted-base
- monad-control
- network
- process
- random
- retry
- safe
- temporary
- text
- time
- transformers
- transformers-base
- unix
- unordered-containers
- webdriver
- HTTP
- HUnit

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

library:
  source-dirs: src
  ghc-options:
    - -W
  exposed-modules:
    - Test.Hspec.WebDriver.Toolkit
    - Test.Hspec.WebDriver.Toolkit.Capabilities
    - Test.Hspec.WebDriver.Toolkit.Expectations
    - Test.Hspec.WebDriver.Toolkit.Waits
    - Test.Hspec.WebDriver.Toolkit.Window

executables:
  hspec-webdriver-toolkit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-webdriver-toolkit

tests:
  hspec-webdriver-toolkit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-webdriver-toolkit
