
resolver: lts-13.18

packages:
- .

extra-deps:
# - webdriver-0.9.0.1 # Earlier versions were failing on simple operations with BadJSON error

- github: codedownio/hs-webdriver
  commit: 8bc94c291838d6d4152138cf4ab94d1db6f8da7e
